[config]
schemaVersion = "0.0.1"


[package]
namespace = "NikkelM"
name = "Randomize_Favorite_Songs"
versionNumber = "3.0.0"
description = "Set songs as favorites with the Music Maker and randomize only from them each time you return to the Crossroads!"
websiteUrl = "https://github.com/NikkelM/Hades-II-MusicMakerRandomizer"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.55"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.0"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", "misc", "audio" ]
